import Head from 'next/head'
import Navbar from '../components/navbar'
import Sidebar from '../components/sidebar'
import '../styles/globals.css'
import {ThemeProvider} from 'next-themes'
import {AnimatePresence} from 'framer-motion'


function MyApp({ Component, pageProps ,router }) {
  return (
    <ThemeProvider attribute="class">
      <div className="grid grid-cols-12 absolute  gap-6 px-5 my-14 lg:mb-0 md:mb-16 sm:px-20 md:px-32 lg:px-36 xl:px-48 " 
     >
        {/* // do this div style later (after putting the content) */}
        <div className="h-full col-span-12  p-4 text-base text-center bg-white dark:bg-dark-500 lg:col-span-3 rounded-2xl shadow-custom-light dark:shadow-custom-dark ">
          {/* //!sidebar */}
          <Sidebar />
        </div>
        <div className="col-span-12 h-full bg-white shadow-custom-light dark:shadow-custom-dark rounded-2xl lg:col-span-9 dark:bg-dark-500">
          {/* //!navbar */}
          <Navbar />
          {/* //!about */}
          <AnimatePresence>
           <Component {...pageProps} key={router.route} />
          </AnimatePresence>
        </div>
      </div>
    </ThemeProvider>
  );
}

export default MyApp;


/*function MyApp({ Component, pageProps }) {

  return( 
    <ThemeProvider attribute='class'>

  <div  className='all w-full  bg-gradient-to-r from-green to-blue-400 dark:from-dark-500 dark:to-dark-700 flex flex-1 '>
      
  <div className='grid grid-cols-12 gap-6 px-5 lg:px-48 my-14 sm:px-20 md:px-32 mt-20 absolute '>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&family=Roboto:ital,wght@1,300;1,700&display=swap" rel="stylesheet"/>
    </Head>
  
    <Sidebar/>
    <div className=' col-span-12 bg-white dark:bg-dark-500 lg:col-span-9 rounded-xl'>
      <Navbar/>
      <Component {...pageProps} />
     

    </div>

 

  
  </div>
  </div>
    </ThemeProvider>

  )
}

export default MyApp
*/